name: Docker

on:
  push:
  pull_request:
    branches: [master]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build -t flashbots/mev-relay-ci .
